### ISSUE TITLE
Need reconnect feature

### ISSUE THREAD

**Issue by samuelyao314** [luca3m/redis3m#12]
When Redis server restart,  redis3m client can't reconnect to svr.

**Comment by fifar** [comment]
I think @samuelyao314 means that if redis server restarts, redis3m connection pool gets a bad redis connection. Because maybe this connection is closed by redis server, which remains CLOSE_WAIT. Is there possible that check redis connection status before retrieve it or let a thread keep all redis connections alive? Thanks.

**Comment by luca3m** [comment]
Hi @fifar 

If you use this function:

```c++
// Automatically retries on connection failures
pool->run_with_connection<void>([&](connection::ptr_t conn)
{
  conn->run(command("SET")("foo")("bar"));
});
```

the pool object will retry your lambda for any connection error, giving you a new `conn` object if needed. I used this way because doesn't need an extra thread, it's passive, and covers a lot of connection errors. I don't understand why it does not work on your use case.
